



CREATE TABLE `DISEASE_DETAILS` (
  `DISEASE_DETAILS_ID` int(11) NOT NULL AUTO_INCREMENT,
  `PHIBASE_SL_ID` int(11) NOT NULL DEFAULT '0',
  `DIS_MULTIPLE_MUTATION` varchar(100) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `DISEASE_NAME` text COLLATE utf8_unicode_ci NOT NULL,
  `DIS_PHENOTYPE_MUTANT` text COLLATE utf8_unicode_ci NOT NULL,
  `DIS_DELV_MACROSCOPICALLY` text COLLATE utf8_unicode_ci NOT NULL,
  `DIS_INDUCER` text COLLATE utf8_unicode_ci NOT NULL,
  `DIS_INDUCER_ID_CAS` text COLLATE utf8_unicode_ci NOT NULL,
  `DIS_HOST_TARGET` varchar(100) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `DIS_HOST_TARGET_ID` varchar(100) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `DIS_INTERACTION_PHENOTYPE` varchar(100) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `DIS_HOST_RESPONSE` text COLLATE utf8_unicode_ci NOT NULL,
  `DIS_EXPERIMENTAL_EVIDENCE` text COLLATE utf8_unicode_ci NOT NULL,
  `DIS_EXP_EVIDENCE_TRANSIENT` varchar(100) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `DIS_COMMENTS` text COLLATE utf8_unicode_ci NOT NULL,
  `CREATE_DATE` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`DISEASE_DETAILS_ID`),
  KEY `DISEASE_DETAILS_FK` (`PHIBASE_SL_ID`),
  CONSTRAINT `DISEASE_DETAILS_FK` FOREIGN KEY (`PHIBASE_SL_ID`) REFERENCES `PHIBASE_ACCESSION_DETAILS` (`PHIBASE_SL_ID`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci; 





CREATE TABLE `DISEASE_INTERVENTION` (
  `DISEASE_INTERVENTION_ID` int(11) NOT NULL AUTO_INCREMENT,
  `DISEASE_DETAILS_ID` int(11) NOT NULL DEFAULT '0',
  `DIS_ANTI_INFECTIVE_AGENT_ID_CAS` text COLLATE utf8_unicode_ci NOT NULL,
  `DIS_ANTI_INFECTIVE_AGENT` varchar(200) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `DIS_ANTI_INFECTIVE_COMPOUND` varchar(200) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `DIS_ANTI_INFECTIVE_TARGET_SITE` varchar(200) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `DIS_ANTI_INFECTIVE_GROUP_NAME` varchar(200) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `DIS_ANTI_INFECTIVE_CHEMICAL_GP` varchar(200) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `DIS_ANTI_INFECTIVE_MODE_PL` varchar(200) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `DIS_ANTI_INFECTIVE_FRAC_CODE` varchar(100) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `DIS_ANTI_INFECTIVE_COMMENT` varchar(200) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `CREATE_DATE` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`DISEASE_INTERVENTION_ID`),
  KEY `DISEASE_INTERVENTION_FK` (`DISEASE_DETAILS_ID`),
  CONSTRAINT `DISEASE_INTERVENTION_FK` FOREIGN KEY (`DISEASE_DETAILS_ID`) REFERENCES `DISEASE_DETAILS` (`DISEASE_DETAILS_ID`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci; 





CREATE TABLE `DISEASE_PROCESS` (
  `DISEASE_PROCESS_ID` int(11) NOT NULL AUTO_INCREMENT,
  `DISEASE_DETAILS_ID` int(11) NOT NULL DEFAULT '0',
  `DIS_MATING_DEFECT_PRI_PENETRATION` varchar(100) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `DIS_PRE_PENETRATION_DEFECT` varchar(100) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `DIS_PENETRATION_DEFECT` varchar(100) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `DIS_POST_PENETRATION_DEFECT` varchar(100) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `DIS_VEGETATIVE_SPORES` varchar(100) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `DIS_SEXUAL_SPORES` varchar(100) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `DIS_INVITRO_GROWTH` varchar(100) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `DIS_SPORE_GERMINATION` varchar(100) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `CREATE_DATE` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`DISEASE_PROCESS_ID`),
  KEY `DISEASE_PROCESS_FK` (`DISEASE_DETAILS_ID`),
  CONSTRAINT `DISEASE_PROCESS_FK` FOREIGN KEY (`DISEASE_DETAILS_ID`) REFERENCES `DISEASE_DETAILS` (`DISEASE_DETAILS_ID`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci; 





CREATE TABLE `GENE_DETAILS` (
  `GENE_DETAILS_ID` int(11) NOT NULL AUTO_INCREMENT,
  `PHIBASE_SL_ID` int(11) NOT NULL DEFAULT '0',
  `IDENTIFIER_TYPE_GN_PROTEIN_ID` text COLLATE utf8_unicode_ci NOT NULL,
  `GN_PROTEIN_ID` varchar(100) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `IDENTIFIER_TYPE_GN_LOCUS_ID` text COLLATE utf8_unicode_ci NOT NULL,
  `GN_LOCUS_ID` varchar(100) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `AA_GN_SEQUENCE` text COLLATE utf8_unicode_ci NOT NULL,
  `NT_GN_SEQUENCE` text COLLATE utf8_unicode_ci NOT NULL,
  `GN_STRAIN` varchar(100) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `GN_NAME` varchar(100) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `GN_LOCATION` varchar(100) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `GN_MODIFICATION` varchar(200) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `GN_MODIFIED_ID` varchar(100) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `GN_INTERACTING_PARTNER` varchar(100) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `GN_INTERACTING_PARTNER_ID` varchar(100) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `GN_FUNCTION_NAME` text COLLATE utf8_unicode_ci NOT NULL,
  `GN_GO_ANNO_ID` text COLLATE utf8_unicode_ci NOT NULL,
  `GN_DATABASE` varchar(100) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `GN_PATHWAY_SECRETION_SYSTEM` text COLLATE utf8_unicode_ci NOT NULL,
  `ESS_GN_LETHAL_KNOCKOUT` varchar(100) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `CREATE_DATE` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`GENE_DETAILS_ID`),
  KEY `GENE_DETAILS_FK` (`PHIBASE_SL_ID`),
  CONSTRAINT `GENE_DETAILS_FK` FOREIGN KEY (`PHIBASE_SL_ID`) REFERENCES `PHIBASE_ACCESSION_DETAILS` (`PHIBASE_SL_ID`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci; 





CREATE TABLE `HOST_DETAILS` (
  `HOST_DETAILS_ID` int(11) NOT NULL AUTO_INCREMENT,
  `PHIBASE_SL_ID` int(11) NOT NULL DEFAULT '0',
  `HST_MONOCOT_DICOT_PLANT` varchar(100) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `HST_NCBI_TAXONOMY_ID` varchar(100) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `HST_EXPERIMENTAL_SPECIES` varchar(100) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `HST_TISSUE_TYPE` varchar(100) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `HOST_STRAIN_GENOTYPE` varchar(100) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `HST_GENO_TYPE` varchar(100) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `HST_GENOTYPE_ID` varchar(100) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `CREATE_DATE` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`HOST_DETAILS_ID`),
  KEY `HOST_DETAILS_FK` (`PHIBASE_SL_ID`),
  CONSTRAINT `HOST_DETAILS_FK` FOREIGN KEY (`PHIBASE_SL_ID`) REFERENCES `PHIBASE_ACCESSION_DETAILS` (`PHIBASE_SL_ID`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci; 





CREATE TABLE `INFO_NOT_DISPLAY` (
  `INFO_NOT_DISPLAY_ID` int(11) NOT NULL AUTO_INCREMENT,
  `PHIBASE_SL_ID` int(11) NOT NULL DEFAULT '0',
  `SPECIES_EXPERT` varchar(100) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `ENTERED_BY` varchar(100) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `MANUAL_M_OR_TEXT_MINING_T` varchar(100) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `CURATOR_ORGANIZATION` text COLLATE utf8_unicode_ci NOT NULL,
  `CURATION_DATE` varchar(100) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `CURATION_COMMENTS` text COLLATE utf8_unicode_ci NOT NULL,
  `TO_DO` varchar(100) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `RECORD_ID` varchar(100) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `CURATION_DETAILS` text COLLATE utf8_unicode_ci NOT NULL,
  `PDF_FILE_NAME` text COLLATE utf8_unicode_ci NOT NULL,
  `BATCH_NO` varchar(100) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `LAB` text COLLATE utf8_unicode_ci NOT NULL,
  `FG_MYCOTOXIN` varchar(100) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  PRIMARY KEY (`INFO_NOT_DISPLAY_ID`),
  KEY `INFO_NOT_DISPLAY_FK` (`PHIBASE_SL_ID`),
  CONSTRAINT `INFO_NOT_DISPLAY_FK` FOREIGN KEY (`PHIBASE_SL_ID`) REFERENCES `PHIBASE_ACCESSION_DETAILS` (`PHIBASE_SL_ID`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci; 





CREATE TABLE `PATHOGEN_DETAILS` (
  `PATHOGEN_DETAILS_ID` int(11) NOT NULL AUTO_INCREMENT,
  `GENE_DETAILS_ID` int(11) NOT NULL DEFAULT '0',
  `PG_SPECIES_TAXONOMY_ID` varchar(100) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `PG_STRAIN_TAXONOMY_ID` varchar(100) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `PATHOGEN_SPECIES` varchar(100) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `PG_EXPERIMENTAL_STRAIN` varchar(100) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `CREATE_DATE` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`PATHOGEN_DETAILS_ID`),
  KEY `PATHOGEN_DETAILS_FK` (`GENE_DETAILS_ID`),
  CONSTRAINT `PATHOGEN_DETAILS_FK` FOREIGN KEY (`GENE_DETAILS_ID`) REFERENCES `GENE_DETAILS` (`GENE_DETAILS_ID`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci; 





CREATE TABLE `PHIBASE_ACCESSION_DETAILS` (
  `PHIBASE_SL_ID` int(11) NOT NULL AUTO_INCREMENT,
  `PHIBASE_ACCESSION_ID` varchar(100) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `CREATE_DATE` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`PHIBASE_SL_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci; 





CREATE TABLE `PHIBASE_ACCESSION_GENE_MAPPING` (
  `PHIBASE_ACCESSION_GENE_ID` int(11) NOT NULL AUTO_INCREMENT,
  `PHIBASE_SL_ID` int(11) NOT NULL,
  `PHIBASE_ACCESSION_ID` varchar(45) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `GENE_NAME` varchar(100) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  PRIMARY KEY (`PHIBASE_ACCESSION_GENE_ID`),
  KEY `PHIBASE_ACCESSION_GENE_MAPPING_FK_idx` (`PHIBASE_SL_ID`),
  CONSTRAINT `PHIBASE_ACCESSION_GENE_MAPPING_FK` FOREIGN KEY (`PHIBASE_SL_ID`) REFERENCES `PHIBASE_ACCESSION_DETAILS` (`PHIBASE_SL_ID`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8; 





CREATE TABLE `REFERENCE` (
  `REFERENCE_ID` int(11) NOT NULL AUTO_INCREMENT,
  `PHIBASE_SL_ID` int(11) NOT NULL DEFAULT '0',
  `LITERATURE_ID` varchar(100) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `LIT_SOURCE` varchar(100) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `LIT_YEAR` varchar(20) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `DOI` text COLLATE utf8_unicode_ci NOT NULL,
  `FULL_CITATION` text COLLATE utf8_unicode_ci NOT NULL,
  `AUTHOR_MAIL` text COLLATE utf8_unicode_ci NOT NULL,
  `REFERENCE` varchar(100) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `CREATE_DATE` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`REFERENCE_ID`),
  KEY `REFERENCE_FK` (`PHIBASE_SL_ID`),
  CONSTRAINT `REFERENCE_FK` FOREIGN KEY (`PHIBASE_SL_ID`) REFERENCES `PHIBASE_ACCESSION_DETAILS` (`PHIBASE_SL_ID`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci; 